name: 'PR Checks'
permissions:
  contents: read

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  run-reflect:
    uses: ./.github/workflows/reflect-tests.yml
    with:
      suite_id: 'vg-test'
    secrets:
      reflect_api_key: ${{ secrets.REFLECT_API_KEY }}
